import { OfficialAirline } from './bookingUtils';

// Deterministic test dataset with verified fields (manually curated)
export const TEST_AIRLINES: OfficialAirline[] = [
  {
    id: 'emirates',
    name: 'طيران الإمارات (Emirates)',
    nameEn: 'Emirates Airline',
    country: 'United Arab Emirates',
    logo: '🇦🇪 ✈️',
    officialBookingUrl: 'https://www.emirates.com',
    webCheckinUrl: 'https://www.emirates.com/english/manage-booking/online-check-in/',
    baggagePolicyUrl: 'https://www.emirates.com/english/before-you-fly/baggage/',
    directBenefits: [],
    iataCode: 'EK',
    icaoCode: 'UAE',
    serviceLevel: 'PREMIUM',
    businessModel: 'FULL_SERVICE',
    operationType: 'PASSENGER',
    networkType: 'GLOBAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'qatar',
    name: 'الخطوط الجوية القطرية (Qatar Airways)',
    nameEn: 'Qatar Airways',
    country: 'قطر',
    logo: '🇶🇦 ✈️',
    officialBookingUrl: 'https://www.qatarairways.com',
    webCheckinUrl: 'https://www.qatarairways.com/en/check-in.html',
    baggagePolicyUrl: 'https://www.qatarairways.com/en/baggage.html',
    directBenefits: [],
    iataCode: 'QR',
    icaoCode: 'QTR',
    serviceLevel: 'PREMIUM',
    businessModel: 'FULL_SERVICE',
    operationType: 'PASSENGER',
    networkType: 'GLOBAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'saudia',
    name: 'الخطوط الجوية العربية السعودية (Saudia)',
    nameEn: 'Saudia Airlines',
    country: 'Saudi Arabia',
    logo: '🇸🇦 ✈️',
    officialBookingUrl: 'https://www.saudia.com',
    webCheckinUrl: 'https://www.saudia.com/travel-with-saudia/manage/check-in-online',
    baggagePolicyUrl: 'https://www.saudia.com/travel-with-saudia/baggage',
    directBenefits: [],
    iataCode: 'SV',
    icaoCode: 'SVA',
    serviceLevel: 'STANDARD',
    businessModel: 'HYBRID',
    operationType: 'PASSENGER',
    networkType: 'REGIONAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'egyptair',
    name: 'مصر للطيران (EgyptAir)',
    nameEn: 'EgyptAir',
    country: 'Egypt',
    logo: '🇪🇬 ✈️',
    officialBookingUrl: 'https://www.egyptair.com',
    webCheckinUrl: 'https://www.egyptair.com/ar/fly/Pages/web-checkin.aspx',
    baggagePolicyUrl: 'https://www.egyptair.com/ar/fly/baggage/Pages/baggage-allowance.aspx',
    directBenefits: [],
    iataCode: 'MS',
    icaoCode: 'MSR',
    serviceLevel: 'STANDARD',
    businessModel: 'FULL_SERVICE',
    operationType: 'PASSENGER',
    networkType: 'REGIONAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'turkish',
    name: 'الخطوط الجوية التركية (Turkish Airlines)',
    nameEn: 'Turkish Airlines',
    country: 'Turkey',
    logo: '🇹🇷 ✈️',
    officialBookingUrl: 'https://www.turkishairlines.com',
    webCheckinUrl: 'https://www.turkishairlines.com/en-int/flights/manage-booking/',
    baggagePolicyUrl: 'https://www.turkishairlines.com/en-int/any-questions/baggage-information/',
    directBenefits: [],
    iataCode: 'TK',
    icaoCode: 'THY',
    serviceLevel: 'PREMIUM',
    businessModel: 'FULL_SERVICE',
    operationType: 'PASSENGER',
    networkType: 'GLOBAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'lufthansa',
    name: 'لوفتهانزا (Lufthansa)',
    nameEn: 'Lufthansa',
    country: 'Germany',
    logo: '🇩🇪 ✈️',
    officialBookingUrl: 'https://www.lufthansa.com',
    webCheckinUrl: 'https://www.lufthansa.com/de/en/online-check-in',
    baggagePolicyUrl: 'https://www.lufthansa.com/de/en/baggage-overview',
    directBenefits: [],
    iataCode: 'LH',
    icaoCode: 'DLH',
    serviceLevel: 'PREMIUM',
    businessModel: 'FULL_SERVICE',
    operationType: 'PASSENGER',
    networkType: 'GLOBAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'british_airways',
    name: 'الخطوط الجوية البريطانية (British Airways)',
    nameEn: 'British Airways',
    country: 'United Kingdom',
    logo: '🇬🇧 ✈️',
    officialBookingUrl: 'https://www.britishairways.com',
    webCheckinUrl: 'https://www.britishairways.com/travel/olcilandingpage/public/en_gb',
    baggagePolicyUrl: 'https://www.britishairways.com/en-gb/information/baggage-essentials',
    directBenefits: [],
    iataCode: 'BA',
    icaoCode: 'BAW',
    serviceLevel: 'PREMIUM',
    businessModel: 'FULL_SERVICE',
    operationType: 'PASSENGER',
    networkType: 'GLOBAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'airfrance',
    name: 'الخطوط الجوية الفرنسية (Air France)',
    nameEn: 'Air France',
    country: 'France',
    logo: '🇫🇷 ✈️',
    officialBookingUrl: 'https://www.airfrance.com',
    webCheckinUrl: 'https://www.airfrance.fr/en/check-in',
    baggagePolicyUrl: 'https://www.airfrance.fr/en/information/bagages',
    directBenefits: [],
    iataCode: 'AF',
    icaoCode: 'AFR',
    serviceLevel: 'PREMIUM',
    businessModel: 'FULL_SERVICE',
    operationType: 'PASSENGER',
    networkType: 'GLOBAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'flynas',
    name: 'طيران ناس (flynas)',
    nameEn: 'flynas',
    country: 'Saudi Arabia',
    logo: '🟡 ✈️',
    officialBookingUrl: 'https://www.flynas.com',
    webCheckinUrl: 'https://www.flynas.com/ar/check-in',
    baggagePolicyUrl: 'https://www.flynas.com/ar/baggage-services',
    directBenefits: [],
    iataCode: 'XY',
    icaoCode: 'KNE',
    serviceLevel: 'ECONOMY',
    businessModel: 'LOW_COST',
    operationType: 'PASSENGER',
    networkType: 'REGIONAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'flyadeal',
    name: 'طيران أديل (flyadeal)',
    nameEn: 'flyadeal',
    country: 'Saudi Arabia',
    logo: '🟣 ✈️',
    officialBookingUrl: 'https://www.flyadeal.com',
    webCheckinUrl: 'https://www.flyadeal.com/ar/check-in',
    baggagePolicyUrl: 'https://www.flyadeal.com/ar/baggage-policy',
    directBenefits: [],
    // IATA/ICAO intentionally left blank here to avoid inventing data
    serviceLevel: 'ECONOMY',
    businessModel: 'LOW_COST',
    operationType: 'PASSENGER',
    networkType: 'REGIONAL',
    verified: false, // not fully verified in this dataset
    confidence: 0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'wizzair',
    name: 'Wizz Air',
    nameEn: 'Wizz Air',
    country: 'Hungary',
    logo: '🇭🇺 ✈️',
    officialBookingUrl: 'https://wizzair.com',
    webCheckinUrl: '',
    baggagePolicyUrl: '',
    directBenefits: [],
    iataCode: 'W6',
    icaoCode: 'WZZ',
    serviceLevel: 'ECONOMY',
    businessModel: 'LOW_COST',
    operationType: 'PASSENGER',
    networkType: 'REGIONAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'ryanair',
    name: 'Ryanair',
    nameEn: 'Ryanair',
    country: 'Ireland',
    logo: '🇮🇪 ✈️',
    officialBookingUrl: 'https://www.ryanair.com',
    webCheckinUrl: '',
    baggagePolicyUrl: '',
    directBenefits: [],
    iataCode: 'FR',
    icaoCode: 'RYR',
    serviceLevel: 'ECONOMY',
    businessModel: 'LOW_COST',
    operationType: 'PASSENGER',
    networkType: 'REGIONAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'easyjet',
    name: 'easyJet',
    nameEn: 'easyJet',
    country: 'United Kingdom',
    logo: '🇬🇧 ✈️',
    officialBookingUrl: 'https://www.easyjet.com',
    webCheckinUrl: '',
    baggagePolicyUrl: '',
    directBenefits: [],
    iataCode: 'U2',
    icaoCode: 'EZY',
    serviceLevel: 'ECONOMY',
    businessModel: 'LOW_COST',
    operationType: 'PASSENGER',
    networkType: 'REGIONAL',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
];
