import { OfficialHotelChain } from './bookingUtils';

export const TEST_HOTELS: OfficialHotelChain[] = [
  {
    id: 'marriott',
    name: 'ماريوت الدولية (Marriott Bonvoy)',
    logo: '🏨 🌟',
    officialBookingUrl: 'https://www.marriott.com',
    bestRateGuarantee: true,
    earlyCheckinAssistance: true,
    whatsappAvailable: true,
    samplePhone: '+966-11-211-5555',
    directBenefits: [],
    serviceLevel: 'PREMIUM',
    propertyType: 'HOTEL',
    starRating: 5,
    hotelSegment: 'BUSINESS',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'fourseasons',
    name: 'فور سيزونز (Four Seasons)',
    logo: '🏨 🌳',
    officialBookingUrl: 'https://www.fourseasons.com',
    bestRateGuarantee: true,
    earlyCheckinAssistance: true,
    whatsappAvailable: true,
    samplePhone: '+966-11-211-5000',
    directBenefits: [],
    serviceLevel: 'LUXURY',
    propertyType: 'HOTEL',
    starRating: 5,
    hotelSegment: 'LUXURY',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'rixos',
    name: 'ريكسوس ريزورت (Rixos Resort)',
    logo: '🏖️',
    officialBookingUrl: 'https://www.rixos.com',
    bestRateGuarantee: false,
    earlyCheckinAssistance: false,
    whatsappAvailable: false,
    samplePhone: '',
    directBenefits: [],
    serviceLevel: 'LUXURY',
    propertyType: 'RESORT',
    starRating: 5,
    hotelSegment: 'BEACH_RESORT',
    verified: true,
    confidence: 1.0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
  {
    id: 'hostel_generic',
    name: 'Hostel (Generic)',
    logo: '🛏️',
    officialBookingUrl: '',
    bestRateGuarantee: false,
    earlyCheckinAssistance: false,
    whatsappAvailable: false,
    samplePhone: '',
    directBenefits: [],
    serviceLevel: 'BUDGET',
    propertyType: 'HOSTEL',
    hotelSegment: 'BUDGET_TRAVEL',
    verified: false,
    confidence: 0,
    dataSource: 'manual_test_data',
    isActive: true,
  },
];
